FROM openjdk:17-jdk-alpine
COPY target/*.jar hotel-api-gateway-1.0.0.jar
ENTRYPOINT ["java","-jar","/api-gateway-1.0.0.jar"]FROM openjdk:17-jdk-alpine
COPY target/*.jar hotel-api-gateway-1.0.0.jar
ENTRYPOINT ["java","-jar","/api-gateway-1.0.0.jar"]