services:
  eureka-server:
    container_name: eureka-server
    image: eureka-server:latest
    ports:
      - 8761:8761
    networks:
      - ms-network

  api-gateway:
    container_name: api-gateway

    image: api-gateway:latest
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      EUREKA_HOST: eureka-server
    networks:
      - ms-network
    depends_on:
      - eureka-server

  userservice:
    container_name: userservice
    image: userservice:latest
    build:
      context: ../userservices
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      EUREKA_HOST: eureka-server
      MONGO_DB_HOST: mongodb
      MONGO_DB_PORT: 27017
      MONGO_DB_USERNAME: root
      MONGO_DB_PASSWORD: password
    networks:
      - ms-network
    depends_on:
     - eureka-server
  courseservice:
    container_name: courseservice
    image: courseservice:latest
    build:
      context: ../courseservice
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    environment:
      EUREKA_HOST: eureka-server
      MONGO_DB_HOST: mongodb
      MONGO_DB_PORT: 27017
      MONGO_DB_USERNAME: root
      MONGO_DB_PASSWORD: password
    networks:
      - ms-network
    depends_on:
      - eureka-server
 
networks:
  ms-network:
    driver: bridge
